myapp/config/routes.rb
Myapp::Application.routes.draw do

  get '/' => "home#index" , as: :homepage

  get '/about' => "users#about"

  get '/profile' =>"users#profile"

  get '/links' =>"home#links"

end

myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

myapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout 'home_layout'

    def index

    	@post = "Setting a good example for your children takes all the fun out of middle age."

    end
end

myapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    layout 'users_layout'

    def about

    	@orders = {books: 2500, amount: 10600, status: "ordered"}



    end
end

myapp/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp/app/views/home/_post.html.erb
<h1>create a new post </h2>

	  <h2>Student post</h2>

	   <%= @post %>

myapp/app/views/home/index.html.erb
<h1>This is the homepage</h1>

  <%= render "post" %> <br>

  <%= link_to "User Info" , about_path %>

myapp/app/views/home/links.html.erb
<h1>All links go here </h1>

myapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

myapp/app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Homepage</title>
</head>
<body>

   <%= yield %>

</body>
</html>

myapp/app/views/layouts/users_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Users page</title>
</head>
<body>

   <%= yield %>

</body>
</html>

myapp/app/views/users/_orders.html.erb
<h1> Orders for the upcoming year</h1>
  
  <% new_order = @orders %>
  
  <%="Books : " + new_order[:books].to_s %> <br>

  <%= "Amount : "+ "$"+ new_order[:amount].to_s %> <br>

  <%= "Status : " + new_order[:status] %> <br>

  Return to the profile page : <%=  link_to("Profile page", profile_path)%>

myapp/app/views/users/about.html.erb
<h1>This is the User info page </h1>

  <%= render "orders" %>

myapp/app/views/users/profile.html.erb
<h1>this is the profile page </h1>

   <%= link_to "Homepage" ,homepage_path %>